apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ppc
  template:
    metadata:
      labels:
        app: ppc
    spec:
      containers:
      - image: okteto.dev/ppc:latest
        name: ppc
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "4a28be7c-01e6-4537-bde1-97286eb696b8"
        - name: Vless_Path
          value: "/fgnjfudbshdyjytjddju"
        - name: Vmess_UUID
          value: "4a28be7c-01e6-4537-bde1-97286eb696b8"
        - name: Vmess_Path
          value: "/unetyrtudntjryuitstrhsb"
        - name: Share_Path
          value: "/v2link"
